name: Notify resources_ci about new commits in production

on:
  push:
    branches:
      - production

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event deploy_prod
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api repos/ScanMeFindMe/resources_ci/dispatches \
              --raw-field event_type=deploy_prod
