name: Upload Website to staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy static site to S3 bucket staging
        run: aws s3 sync ./texts/ s3://smfm-userdata-staging/texts/ --delete

      - name: Deploy media files to S3 bucket staging
        run: aws s3 sync ./media/ s3://smfm-userdata-staging/media/ --delete