name: Test

on:
  push:
    branches:
      - emails

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: |
          echo "hello"
          pwd
          ls -la
          export lang=en
          export file=trialstart
          export subject=$(head -1 texts/${lang}/email/${file}.md)
          echo "--SUBJECT--"
          echo $subject
          export body=$(tail -n +2 texts/en/email/trialstart.md)
          echo "--BODY--"
          echo $body
          export tmpl='{"Template":{"TemplateName":"{$file}_{$lang}"}}'
          echo "--TEMPLATE--"
          echo $tmpl
          export JSON_STRING=$( jq -n \
                            --arg tn "{$file}_{$lang}" \
                            --arg sb "$subject" \
                            --arg bd "$body" \
                            '{Template: {TemplateName: $tn, SubjectPart: $sb, HtmlPart: $bd}' )
          echo "--JSON_STRING--"
          echo $JSON_STRING
          echo ::set-output name=json_var::'[{ "name": "test", "client_payload": "111" }, { "name": "test2", "client_payload": "222" }] '