name: Test

on:
  push:
    branches:
      - emails

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: |
          echo "hello"
          pwd
          ls -la
          export lang=en
          export file=trialstart
          echo "---------${file}_${lang}-------"
          export subject=$(head -1 texts/${lang}/email/${file}.md)
          export body=$(tail -n +2 texts/${lang}/email/${file}.md)
          export tempfile="${file}_${lang}.json"
          jq -n --arg tn "${file}_${lang}" --arg sb "$subject" --arg bd "$body" \
              '{Template: {TemplateName: $tn, SubjectPart: $sb, HtmlPart: $bd}}' \
              > $tempfile
          cat $tempfile
