name: Test

on:
  push:
    branches:
      - emails

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Updating email templates
        run: |
          for x in texts/**/email/*.md; do
            export lang=$(echo $x | awk -F '/' '{print $2}')
            export file=$(echo $x | awk -F '/' '{print $4}' | awk -F '.' '{print $1}')
            echo "Updating template ${file}_${lang}..."
            export subject=$(head -1 $x)
            export body=$(tail -n +2 $x)
            jq -n --arg tn "${file}_${lang}" --arg sb "$subject" --arg bd "$body" \
                '{Template: {TemplateName: $tn, SubjectPart: $sb, HtmlPart: $bd}}' \
                > temp.json
            aws ses create-template --cli-input-json file://temp.json 2> /dev/null || true
            aws ses update-template --cli-input-json file://temp.json
          done
