name: Test

on:
  push:
    branches:
      - emails

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: |
          for x in texts/**/email/*.md; do
            export lang=$(echo $x | awk -F '/' '{print $2}')
            export file=$(echo $x | awk -F '/' '{print $4}' | awk -F '.' '{print $1}')
            echo "---------${file}_${lang}-------"
            export subject=$(head -1 $x)
            export body=$(tail -n +2 $x)
            export tempfile="${file}_${lang}.json"
            jq -n --arg tn "${file}_${lang}" --arg sb "$subject" --arg bd "$body" \
                '{Template: {TemplateName: $tn, SubjectPart: $sb, HtmlPart: $bd}}' \
                > $tempfile
            cat $tempfile
          done